# Generated by Django 4.0.5 on 2022-06-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del cliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre del cliente')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido del cliente')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del cliente')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del producto')),
            ],
        ),
    ]
