# Generated by Django 4.0.5 on 2022-06-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cliente_idcliente_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(max_length=50, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='IdCliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombreCliente',
            field=models.CharField(max_length=50, verbose_name='NombreCliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='IdProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=50, verbose_name='NombreProducto'),
        ),
    ]
