# Generated by Django 4.0.5 on 2022-06-28 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cliente_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Correo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Direccion'),
            preserve_default=False,
        ),
    ]
